/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        // M3 tokens from docs/DESIGN.md — "Dunas y Océano"
        primary: "#004370",
        "primary-container": "#005b96",
        "on-primary": "#ffffff",
        "on-primary-container": "#abd2ff",
        secondary: "#6f5b3f",
        "secondary-container": "#fadeba",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#756144",
        tertiary: "#1d4a19",
        "tertiary-container": "#35622e",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#a8dc9b",
        surface: "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#414750",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#9ccaff",
        outline: "#717781",
        "outline-variant": "#c1c7d1",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f7f9fb",
        "on-background": "#191c1e",
      },
      fontFamily: {
        headline: ["Montserrat", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        custom: "0.5rem",
      },
      boxShadow: {
        sm: "0 1px 2px rgba(0, 0, 0, 0.05)",
        DEFAULT:
          "0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)",
        md: "0 4px 6px -1px rgba(0, 91, 150, 0.08), 0 2px 4px -2px rgba(0, 91, 150, 0.06)",
        lg: "0 10px 15px -3px rgba(0, 91, 150, 0.08), 0 4px 6px -4px rgba(0, 91, 150, 0.06)",
      },
    },
  },
  plugins: [],
};
