/**
 * Mock places catalog for seed-places.ts — second half (10 Concón businesses).
 *
 * Split from the seed script so every file stays under the 300-line CI limit.
 * Every entry references a valid `categoriaId`, `subcategoriaId` and
 * `barrioId` from the catalog seeded by `seed.ts`.
 */
import type { MockPlace } from "./mock-places";

export const MOCK_PLACES_EXTRA: MockPlace[] = [
  {
    nombre: "Estudio Diseño Mar",
    slug: "estudio-diseno-mar",
    descripcionCorta: "Diseño gráfico y branding para emprendedores.",
    descripcion:
      "Estudio de diseño gráfico: branding, identidad visual, packaging y redes sociales para negocios de Concón y Viña del Mar.",
    categoriaId: "servicios-profesionales",
    subcategoriaId: "disenadores",
    barrioId: "vista-al-mar",
    direccion: "Av. del Mar 2200, Concón",
    telefono: "+56322788991",
    sitioWeb: "https://www.disenomar.cl",
    planId: "gratuito",
    abierto24x7: false,
    servicios: ["wifi", "estacionamiento"],
    metodosPago: ["efectivo", "transferencia"],
    estadoVerificacion: "verificado",
    destacado: false,
  },
  {
    nombre: "Gimnasio Océano Fit",
    slug: "gimnasio-oceano-fit",
    descripcionCorta: "Gimnasio con clases funcionales y máquinas.",
    descripcion:
      "Sala de musculación, cardio, clases dirigidas de crossfit, yoga y spinning frente al mar.",
    categoriaId: "salud-y-bienestar",
    subcategoriaId: "gimnasios-y-entrenamiento",
    barrioId: "la-costa",
    direccion: "Av. Borgoño 13400, Concón",
    telefono: "+56322456712",
    sitioWeb: "https://www.oceanofit.cl",
    planId: "gratuito",
    abierto24x7: false,
    servicios: ["wifi", "estacionamiento", "acceso-discapacidad"],
    metodosPago: ["efectivo", "debito", "credito", "transferencia"],
    estadoVerificacion: "verificado",
    destacado: true,
  },
  {
    nombre: "Kinesiología Concón",
    slug: "kinesiologia-concon",
    descripcionCorta: "Fisioterapia, kinesiología deportiva y rehabilitación.",
    descripcion:
      "Centro de kinesiología con foco en rehabilitación de lesiones deportivas, terapia manual y kinesiología respiratoria.",
    categoriaId: "salud-y-bienestar",
    subcategoriaId: "fisioterapia-y-kinesiologia",
    barrioId: "concon-sur",
    direccion: "Av. Concón 2300, Concón",
    telefono: "+56322456789",
    sitioWeb: "https://www.kinesiologiaconcon.cl",
    planId: "gratuito",
    abierto24x7: false,
    servicios: ["acceso-discapacidad", "reservas"],
    metodosPago: ["efectivo", "debito", "credito", "transferencia"],
    estadoVerificacion: "verificado",
    destacado: false,
  },
  {
    nombre: "Instituto Idiomas Pacífico",
    slug: "instituto-idiomas-pacifico",
    descripcionCorta: "Cursos de inglés y otros idiomas.",
    descripcion:
      "Academia de idiomas con cursos de inglés, francés y portugués para niños, jóvenes y adultos.",
    categoriaId: "educacion-y-talleres",
    subcategoriaId: "idiomas",
    barrioId: "higuerillas",
    direccion: "Av. Higuerillas 1800, Concón",
    telefono: "+56322345612",
    sitioWeb: "https://www.idiomaspacifico.cl",
    planId: "gratuito",
    abierto24x7: false,
    servicios: ["wifi", "estacionamiento"],
    metodosPago: ["efectivo", "transferencia", "qr"],
    estadoVerificacion: "verificado",
    destacado: false,
  },
  {
    nombre: "Jardín Infantil Estrellita",
    slug: "jardin-infantil-estrellita",
    descripcionCorta: "Educación inicial y sala cuna.",
    descripcion:
      "Jardín infantil y sala cuna con programa bilingüe, patio exterior y alimentación saludable.",
    categoriaId: "educacion-y-talleres",
    subcategoriaId: "jardines-infantiles",
    barrioId: "villa-concon",
    direccion: "Pasaje Los Aromos 120, Concón",
    telefono: "+56322345678",
    sitioWeb: "https://www.jardinestrellita.cl",
    planId: "gratuito",
    abierto24x7: false,
    servicios: ["estacionamiento", "ninos-bienvenida"],
    metodosPago: ["efectivo", "transferencia"],
    estadoVerificacion: "verificado",
    destacado: false,
  },
  {
    nombre: "Biblioteca Municipal Concón",
    slug: "biblioteca-municipal-concon",
    descripcionCorta: "Biblioteca pública, lectura y actividades culturales.",
    descripcion:
      "Biblioteca municipal con colección general, hemeroteca, sala infantil y actividades de fomento lector.",
    categoriaId: "instituciones-y-organizaciones",
    subcategoriaId: "biblioteca-y-cultura",
    barrioId: "rpc",
    direccion: "Av. Constitución 10, Concón",
    planId: "gratuito",
    abierto24x7: false,
    servicios: ["wifi", "acceso-discapacidad"],
    metodosPago: [],
    estadoVerificacion: "pendiente",
    destacado: false,
  },
  {
    nombre: "Taller Mecánico El Martillo",
    slug: "taller-mecanico-el-martillo",
    descripcionCorta: "Mecánica general y mantención de vehículos.",
    descripcion:
      "Taller mecánico con atención de mecánica general, mantenciones programadas, frenos y suspensión.",
    categoriaId: "movilidad-y-transporte",
    subcategoriaId: "talleres-mecanicos",
    barrioId: "enap",
    direccion: "Ruta 215, km 12, Concón",
    telefono: "+56322456890",
    planId: "gratuito",
    abierto24x7: false,
    servicios: ["estacionamiento"],
    metodosPago: ["efectivo", "transferencia"],
    estadoVerificacion: "pendiente",
    destacado: false,
  },
  {
    nombre: "Transfer Turismo Concón",
    slug: "transfer-turismo-concon",
    descripcionCorta: "Transfers aeropuerto y city tours.",
    descripcion:
      "Servicio de transfers al aeropuerto de Santiago, traslados privados y tours por la costa de Valparaíso.",
    categoriaId: "movilidad-y-transporte",
    subcategoriaId: "taxis-y-transfers",
    barrioId: "los-romeros",
    direccion: "Av. Los Romeros 300, Concón",
    telefono: "+56987654321",
    whatsapp: "+56987654321",
    sitioWeb: "https://www.transferconcon.cl",
    planId: "premium",
    abierto24x7: true,
    servicios: ["delivery"],
    metodosPago: ["efectivo", "transferencia", "qr"],
    estadoVerificacion: "verificado",
    destacado: true,
  },
  {
    nombre: "Veterinaria Amigo Fiel",
    slug: "veterinaria-amigo-fiel",
    descripcionCorta: "Atención veterinaria y peluquería de mascotas.",
    descripcion:
      "Clínica veterinaria con consultas, vacunas, cirugías menores, peluquería canina y venta de alimento premium.",
    categoriaId: "comercio",
    subcategoriaId: "mascotas",
    barrioId: "las-gaviotas",
    direccion: "Av. Las Gaviotas 450, Concón",
    telefono: "+56322345901",
    whatsapp: "+56322345901",
    sitioWeb: "https://www.veterinariaamigofiel.cl",
    planId: "gratuito",
    abierto24x7: false,
    servicios: ["reservas", "apto-mascotas"],
    metodosPago: ["efectivo", "debito", "credito", "transferencia"],
    estadoVerificacion: "verificado",
    destacado: false,
  },
  {
    nombre: "Panadería La Espiga Dorada",
    slug: "panaderia-la-espiga-dorada",
    descripcionCorta: "Panadería y pastelería artesanal.",
    descripcion:
      "Pan amasado artesanal, marraquetas, tortas y dulces horneados a diario. Venta al paso y encargos.",
    categoriaId: "gastronomia",
    subcategoriaId: "panaderias-y-pastelerias",
    barrioId: "concon-ii",
    direccion: "Av. Concón 3450, Concón",
    telefono: "+56322456012",
    sitioWeb: "https://www.laespigadorada.cl",
    planId: "gratuito",
    abierto24x7: false,
    servicios: ["take-away", "delivery"],
    metodosPago: ["efectivo", "debito", "transferencia", "qr"],
    estadoVerificacion: "pendiente",
    destacado: false,
  },
];
